"""LangGraph checkpointer catalog model: graph_checkpoints.

Per ARCHITECTURE.md §7.9, the ``graph_checkpoints`` DDL is owned and created by
the LangGraph Postgres checkpointer's own ``setup()`` routine (invoked from a
dedicated Alembic revision), NOT by the application's autogenerated migrations.

To keep that boundary clean, this model is declared on a SEPARATE metadata
(``CheckpointBase``) so it never enters ``app.db.base.Base.metadata`` and is
therefore excluded from application autogenerate/create_all. It exists purely to
document the shape and to allow read-only ORM access if ever required.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

import sqlalchemy as sa
from sqlalchemy import MetaData, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.models.base import NAMING_CONVENTION


class CheckpointBase(DeclarativeBase):
    """Isolated metadata for checkpointer-owned tables (not app-managed)."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class GraphCheckpoint(CheckpointBase):
    """Catalog of the LangGraph Postgres checkpointer store (library-owned)."""

    __tablename__ = "graph_checkpoints"

    thread_id: Mapped[str] = mapped_column(primary_key=True)
    checkpoint_ns: Mapped[str] = mapped_column(primary_key=True, server_default="")
    checkpoint_id: Mapped[str] = mapped_column(primary_key=True)
    parent_checkpoint_id: Mapped[str | None] = mapped_column(nullable=True)
    checkpoint: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    metadata_: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")
    )
    created_at: Mapped[datetime] = mapped_column(
        sa.TIMESTAMP(timezone=True), server_default=func.now(), nullable=False
    )


__all__ = ["CheckpointBase", "GraphCheckpoint"]
